apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  template:
    spec:
      containers:
      - name: gitlab
        resources:
          requests:
            memory: "3Gi"
            cpu: "1500m"
          limits:
            memory: "5Gi"
            cpu: "2000m"