apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  template:
    spec:
      containers:
      - name: gitlab
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"