apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: gitlab
type: Opaque
data:
  # GitLab root password (base64 encoded) - CHANGE THIS IN PRODUCTION
  # Password: admin123 (simple, with weak password blocking disabled)
  GITLAB_ROOT_PASSWORD: YWRtaW4xMjM=
  # GitLab database secrets
  # Password: gitlabpassword
  GITLAB_DB_PASSWORD: Z2l0bGFicGFzc3dvcmQ=
  # Redis password
  # Password: redispassword
  GITLAB_REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  GITLAB_OMNIBUS_CONFIG: |
    external_url 'http://gitlab-service.gitlab.svc.cluster.local'

    # Database configuration
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'utf8'
    gitlab_rails['db_database'] = 'gitlabhq_production'
    gitlab_rails['db_username'] = 'postgres'
    gitlab_rails['db_password'] = File.read('/etc/gitlab/postgres_password').strip
    gitlab_rails['db_host'] = 'postgresql-service.gitlab.svc.cluster.local'
    gitlab_rails['db_port'] = 5432

    # Redis configuration
    gitlab_rails['redis_host'] = 'redis-service.gitlab.svc.cluster.local'
    gitlab_rails['redis_port'] = 6379
    gitlab_rails['redis_password'] = File.read('/etc/gitlab/redis_password').strip

    # Disable prometheus for smaller deployment
    prometheus['enable'] = false
    prometheus['prometheus_mmap_enable'] = false
    grafana['enable'] = false

    # Disable unnecessary services
    pages['enable'] = false
    registry['enable'] = false
    packages['enable'] = false
    mattermost['enable'] = false
    ci_gitlab_runner['enable'] = false
    elasticsearch['enable'] = false
    kerberos['enable'] = false

    # Keep LFS enabled as requested
    gitlab_rails['lfs_enabled'] = true

    # Disable Prometheus mmap to prevent 500 errors
    gitlab_rails['prometheus_client_mmap_enable'] = false

    # Fix shared memory and tmpfs issues
    gitlab_rails['shared_tmpdir'] = '/tmp'
    gitlab_rails['dir'] = '/var/opt/gitlab'
    gitlab_rails['runtime_dir'] = '/var/opt/gitlab'

    # Disable metrics collection completely to avoid mmap issues
    gitlab_rails['metrics_enabled'] = false
    gitlab_rails['influxdb_enabled'] = false

    # Configure Puma to avoid shared memory issues
    puma['worker_processes'] = 2
    puma['min_threads'] = 2
    puma['max_threads'] = 4
    puma['tmpdir'] = '/tmp'
    puma['state_path'] = '/tmp/puma.state'
    puma['pidfile'] = '/tmp/puma.pid'

    # Optimize Sidekiq for CI/CD workloads and disable metrics
    sidekiq['min_concurrency'] = 2
    sidekiq['max_concurrency'] = 4
    sidekiq['concurrency'] = 2
    sidekiq['metrics_enabled'] = false
    sidekiq['health_checks_enabled'] = true

    # Optimize database for CI/CD
    gitlab_rails['db_pool'] = 10
    gitlab_rails['db_prepared_statements'] = true

    # Optimize Redis for CI/CD caching
    gitlab_rails['redis_cache_enable'] = true
    gitlab_rails['redis_shared_state_enable'] = false

    # Keep artifacts for CI/CD
    gitlab_rails['artifacts_enabled'] = true
    gitlab_rails['artifacts_expiration_period'] = '30 days'

    # Optimize timeouts for CI/CD
    gitlab_rails['webhook_timeout'] = 30
    gitlab_rails['git_timeout'] = 60

    # Disable weak password blocking feature flag
    gitlab_rails['block_weak_passwords'] = false

    # SMTP configuration (optional)
    # gitlab_rails['smtp_enable'] = true
    # gitlab_rails['smtp_address'] = "smtp.gmail.com"
    # gitlab_rails['smtp_port'] = 587
    # gitlab_rails['smtp_user_name'] = "your.email@gmail.com"
    # gitlab_rails['smtp_password'] = "your-password"
    # gitlab_rails['smtp_domain'] = "smtp.gmail.com"
    # gitlab_rails['smtp_authentication'] = "login"
    # gitlab_rails['smtp_enable_starttls_auto'] = true
    # gitlab_rails['smtp_tls'] = false
    # gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        env:
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_ROOT_PASSWORD
        # Disable prometheus multiproc directory to avoid mmap issues
        - name: PROMETHEUS_MULTIPROC_DIR
          value: ""
        - name: PROMETHEUS_EXPORTER
          value: "false"
        # Disable all prometheus client metrics
        - name: RUBY_PROMETHEUS_EXPORTER
          value: "false"
        - name: GITLAB_PROMETHEUS_EXPORTER
          value: "false"
        # Set temp directory
        - name: TMPDIR
          value: "/tmp"
        volumeMounts:
        - name: gitlab-config-storage
          mountPath: /etc/gitlab
        - name: gitlab-data-storage
          mountPath: /var/opt/gitlab
        - name: gitlab-logs-storage
          mountPath: /var/log/gitlab
        - name: gitlab-secret-volume
          mountPath: /etc/gitlab/postgres_password
          subPath: GITLAB_DB_PASSWORD
        - name: gitlab-secret-volume
          mountPath: /etc/gitlab/redis_password
          subPath: GITLAB_REDIS_PASSWORD
        resources: {}
      volumes:
      - name: gitlab-config-storage
        persistentVolumeClaim:
          claimName: gitlab-config-pvc
      - name: gitlab-data-storage
        persistentVolumeClaim:
          claimName: gitlab-data-pvc
      - name: gitlab-logs-storage
        persistentVolumeClaim:
          claimName: gitlab-logs-pvc
      - name: gitlab-secret-volume
        secret:
          secretName: gitlab-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh-service
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  type: ClusterIP